on:
  push:
    branches:
      - master
    paths-ignore:
      - 'tests/**'
      - 'cmake/**'
      - 'extern/**'

name: Build documentation

jobs:
  build-spec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add Pretty CSS
      uses: wei/wget@v1
      with:
        args: -O docs/doxygen-awesome.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: docs/

    - name: Change permissions
      run: sudo chmod 777 docs/html

    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/html
        target-folder: docs/
        clean: true # Automatically remove deleted files from the deploy branch
